0x00-python-hello_world

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,13 @@
 #!/bin/bash
-python3 $PYFILE
+
+# Check if the environment variable $PYFILE is set
+if [ -z "$PYFILE" ]; then
+    echo "Error: The environment variable \$PYFILE is not set."
+    exit 1
+fi
+
+# Check if the specified Python file exists
+if [ ! -f "$PYFILE" ]; then
+    echo "Error: Python file '$PYFILE' not found."
+    exit 1
+fi
